const example = {
    "location": {
      "name": "Ottawa",
      "region": "Ontario",
      "country": "Canada",
      "lat": 45.42,
      "lon": -75.7,
      "tz_id": "America/Toronto",
      "localtime_epoch": 1706922774,
      "localtime": "2024-02-02 20:12"
    },
    "current": {
      "last_updated_epoch": 1706922000,
      "last_updated": "2024-02-02 20:00",
      "temp_c": -4.4,
      "temp_f": 24,
      "is_day": 0,
      "condition": {
        "text": "Overcast ",
        "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
        "code": 1009
      },
      "wind_mph": 5.6,
      "wind_kph": 9,
      "wind_degree": 345,
      "wind_dir": "NNW",
      "pressure_mb": 1021,
      "pressure_in": 30.14,
      "precip_mm": 0,
      "precip_in": 0,
      "humidity": 90,
      "cloud": 90,
      "feelslike_c": -8.5,
      "feelslike_f": 16.6,
      "vis_km": 10,
      "vis_miles": 6,
      "uv": 1,
      "gust_mph": 11.7,
      "gust_kph": 18.9
    },
    "forecast": {
      "forecastday": [
        {
          "date": "2024-02-02",
          "date_epoch": 1706832000,
          "day": {
            "maxtemp_c": -0.2,
            "maxtemp_f": 31.6,
            "mintemp_c": -6.2,
            "mintemp_f": 20.8,
            "avgtemp_c": -1.6,
            "avgtemp_f": 29.1,
            "maxwind_mph": 10.1,
            "maxwind_kph": 16.2,
            "totalprecip_mm": 0.05,
            "totalprecip_in": 0,
            "totalsnow_cm": 0,
            "avgvis_km": 8.3,
            "avgvis_miles": 5,
            "avghumidity": 90,
            "daily_will_it_rain": 0,
            "daily_chance_of_rain": 0,
            "daily_will_it_snow": 0,
            "daily_chance_of_snow": 15,
            "condition": {
              "text": "Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
              "code": 1006
            },
            "uv": 2
          },
          "astro": {
            "sunrise": "07:23 AM",
            "sunset": "05:11 PM",
            "moonrise": "12:23 AM",
            "moonset": "10:29 AM",
            "moon_phase": "Last Quarter",
            "moon_illumination": 59,
            "is_moon_up": 0,
            "is_sun_up": 0
          },
          "hour": [
            {
              "time_epoch": 1706850000,
              "time": "2024-02-02 00:00",
              "temp_c": 0.5,
              "temp_f": 32.9,
              "is_day": 0,
              "condition": {
                "text": "Fog",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/248.png",
                "code": 1135
              },
              "wind_mph": 4.3,
              "wind_kph": 6.8,
              "wind_degree": 288,
              "wind_dir": "WNW",
              "pressure_mb": 1010,
              "pressure_in": 29.84,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 97,
              "cloud": 100,
              "feelslike_c": -2.1,
              "feelslike_f": 28.2,
              "windchill_c": -2.1,
              "windchill_f": 28.2,
              "heatindex_c": 0.5,
              "heatindex_f": 32.9,
              "dewpoint_c": 0,
              "dewpoint_f": 32,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 0,
              "vis_miles": 0,
              "gust_mph": 7,
              "gust_kph": 11.3,
              "uv": 1,
              "short_rad": 0,
              "diff_rad": 0
            },
            {
              "time_epoch": 1706853600,
              "time": "2024-02-02 01:00",
              "temp_c": 0.5,
              "temp_f": 33,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 5.1,
              "wind_kph": 8.3,
              "wind_degree": 299,
              "wind_dir": "WNW",
              "pressure_mb": 1011,
              "pressure_in": 29.84,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 96,
              "cloud": 100,
              "feelslike_c": -2.2,
              "feelslike_f": 28,
              "windchill_c": -2.2,
              "windchill_f": 28,
              "heatindex_c": 0.5,
              "heatindex_f": 33,
              "dewpoint_c": -0.1,
              "dewpoint_f": 31.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 8.5,
              "gust_kph": 13.6,
              "uv": 1,
              "short_rad": 0,
              "diff_rad": 0
            },
            {
              "time_epoch": 1706857200,
              "time": "2024-02-02 02:00",
              "temp_c": 0.6,
              "temp_f": 33,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 5.6,
              "wind_kph": 9,
              "wind_degree": 308,
              "wind_dir": "NW",
              "pressure_mb": 1011,
              "pressure_in": 29.85,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 95,
              "cloud": 100,
              "feelslike_c": -2.4,
              "feelslike_f": 27.6,
              "windchill_c": -2.4,
              "windchill_f": 27.6,
              "heatindex_c": 0.6,
              "heatindex_f": 33,
              "dewpoint_c": -0.1,
              "dewpoint_f": 31.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 8.9,
              "gust_kph": 14.4,
              "uv": 1,
              "short_rad": 0,
              "diff_rad": 0
            },
            {
              "time_epoch": 1706860800,
              "time": "2024-02-02 03:00",
              "temp_c": 0.6,
              "temp_f": 33,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 6.3,
              "wind_kph": 10.1,
              "wind_degree": 315,
              "wind_dir": "NW",
              "pressure_mb": 1011,
              "pressure_in": 29.86,
              "precip_mm": 0.01,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 95,
              "cloud": 100,
              "feelslike_c": -2.8,
              "feelslike_f": 27,
              "windchill_c": -2.8,
              "windchill_f": 27,
              "heatindex_c": 0.6,
              "heatindex_f": 33.1,
              "dewpoint_c": -0.2,
              "dewpoint_f": 31.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 67,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 9.9,
              "gust_kph": 15.9,
              "uv": 1,
              "short_rad": 0,
              "diff_rad": 0
            },
            {
              "time_epoch": 1706864400,
              "time": "2024-02-02 04:00",
              "temp_c": 0.4,
              "temp_f": 32.7,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 7.6,
              "wind_kph": 12.2,
              "wind_degree": 324,
              "wind_dir": "NW",
              "pressure_mb": 1012,
              "pressure_in": 29.87,
              "precip_mm": 0.01,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 94,
              "cloud": 100,
              "feelslike_c": -3.4,
              "feelslike_f": 25.9,
              "windchill_c": -3.4,
              "windchill_f": 25.9,
              "heatindex_c": 0.4,
              "heatindex_f": 32.7,
              "dewpoint_c": -0.2,
              "dewpoint_f": 31.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 79,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 11.6,
              "gust_kph": 18.6,
              "uv": 1,
              "short_rad": 0,
              "diff_rad": 0
            },
            {
              "time_epoch": 1706868000,
              "time": "2024-02-02 05:00",
              "temp_c": -0.1,
              "temp_f": 31.8,
              "is_day": 0,
              "condition": {
                "text": "Light freezing rain",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/311.png",
                "code": 1198
              },
              "wind_mph": 8.9,
              "wind_kph": 14.4,
              "wind_degree": 331,
              "wind_dir": "NNW",
              "pressure_mb": 1012,
              "pressure_in": 29.89,
              "precip_mm": 0.01,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 93,
              "cloud": 100,
              "feelslike_c": -4.4,
              "feelslike_f": 24.1,
              "windchill_c": -4.4,
              "windchill_f": 24.1,
              "heatindex_c": -0.1,
              "heatindex_f": 31.8,
              "dewpoint_c": -0.8,
              "dewpoint_f": 30.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 62,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 13.2,
              "gust_kph": 21.3,
              "uv": 1,
              "short_rad": 0,
              "diff_rad": 0
            },
            {
              "time_epoch": 1706871600,
              "time": "2024-02-02 06:00",
              "temp_c": -0.8,
              "temp_f": 30.5,
              "is_day": 0,
              "condition": {
                "text": "Overcast ",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                "code": 1009
              },
              "wind_mph": 9.8,
              "wind_kph": 15.8,
              "wind_degree": 329,
              "wind_dir": "NNW",
              "pressure_mb": 1013,
              "pressure_in": 29.92,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 91,
              "cloud": 100,
              "feelslike_c": -5.4,
              "feelslike_f": 22.3,
              "windchill_c": -5.4,
              "windchill_f": 22.3,
              "heatindex_c": -0.8,
              "heatindex_f": 30.5,
              "dewpoint_c": -2,
              "dewpoint_f": 28.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 14.5,
              "gust_kph": 23.4,
              "uv": 1,
              "short_rad": 0,
              "diff_rad": 0
            },
            {
              "time_epoch": 1706875200,
              "time": "2024-02-02 07:00",
              "temp_c": -1.4,
              "temp_f": 29.5,
              "is_day": 0,
              "condition": {
                "text": "Cloudy ",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                "code": 1006
              },
              "wind_mph": 9.4,
              "wind_kph": 15.1,
              "wind_degree": 332,
              "wind_dir": "NNW",
              "pressure_mb": 1014,
              "pressure_in": 29.94,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 90,
              "cloud": 81,
              "feelslike_c": -6.2,
              "feelslike_f": 20.8,
              "windchill_c": -6.2,
              "windchill_f": 20.8,
              "heatindex_c": -1.4,
              "heatindex_f": 29.5,
              "dewpoint_c": -2.9,
              "dewpoint_f": 26.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 14,
              "gust_kph": 22.5,
              "uv": 1,
              "short_rad": 0,
              "diff_rad": 0
            },
            {
              "time_epoch": 1706878800,
              "time": "2024-02-02 08:00",
              "temp_c": -1.8,
              "temp_f": 28.8,
              "is_day": 1,
              "condition": {
                "text": "Cloudy ",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                "code": 1006
              },
              "wind_mph": 9.8,
              "wind_kph": 15.8,
              "wind_degree": 336,
              "wind_dir": "NNW",
              "pressure_mb": 1015,
              "pressure_in": 29.97,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 90,
              "cloud": 79,
              "feelslike_c": -6.7,
              "feelslike_f": 20,
              "windchill_c": -6.7,
              "windchill_f": 20,
              "heatindex_c": -1.8,
              "heatindex_f": 28.8,
              "dewpoint_c": -3.4,
              "dewpoint_f": 25.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 14.7,
              "gust_kph": 23.7,
              "uv": 1,
              "short_rad": 0,
              "diff_rad": 0
            },
            {
              "time_epoch": 1706882400,
              "time": "2024-02-02 09:00",
              "temp_c": -1.9,
              "temp_f": 28.6,
              "is_day": 1,
              "condition": {
                "text": "Cloudy ",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                "code": 1006
              },
              "wind_mph": 9.4,
              "wind_kph": 15.1,
              "wind_degree": 339,
              "wind_dir": "NNW",
              "pressure_mb": 1016,
              "pressure_in": 29.99,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 90,
              "cloud": 86,
              "feelslike_c": -6.7,
              "feelslike_f": 19.9,
              "windchill_c": -6.7,
              "windchill_f": 19.9,
              "heatindex_c": -1.9,
              "heatindex_f": 28.6,
              "dewpoint_c": -3.6,
              "dewpoint_f": 25.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 14.2,
              "gust_kph": 22.8,
              "uv": 1,
              "short_rad": 8.66,
              "diff_rad": 4.2
            },
            {
              "time_epoch": 1706886000,
              "time": "2024-02-02 10:00",
              "temp_c": -1.5,
              "temp_f": 29.3,
              "is_day": 1,
              "condition": {
                "text": "Partly Cloudy ",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 9.2,
              "wind_kph": 14.8,
              "wind_degree": 342,
              "wind_dir": "NNW",
              "pressure_mb": 1017,
              "pressure_in": 30.02,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 90,
              "cloud": 56,
              "feelslike_c": -6.4,
              "feelslike_f": 20.5,
              "windchill_c": -6.4,
              "windchill_f": 20.5,
              "heatindex_c": -1.5,
              "heatindex_f": 29.3,
              "dewpoint_c": -3.4,
              "dewpoint_f": 25.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 13,
              "gust_kph": 20.9,
              "uv": 2,
              "short_rad": 44.4,
              "diff_rad": 22.44
            },
            {
              "time_epoch": 1706889600,
              "time": "2024-02-02 11:00",
              "temp_c": -1.2,
              "temp_f": 29.8,
              "is_day": 1,
              "condition": {
                "text": "Partly Cloudy ",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 10.1,
              "wind_kph": 16.2,
              "wind_degree": 346,
              "wind_dir": "NNW",
              "pressure_mb": 1017,
              "pressure_in": 30.05,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 88,
              "cloud": 37,
              "feelslike_c": -5.9,
              "feelslike_f": 21.3,
              "windchill_c": -5.9,
              "windchill_f": 21.3,
              "heatindex_c": -1.2,
              "heatindex_f": 29.8,
              "dewpoint_c": -2.9,
              "dewpoint_f": 26.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 13.3,
              "gust_kph": 21.3,
              "uv": 2,
              "short_rad": 97.02,
              "diff_rad": 46.18
            },
            {
              "time_epoch": 1706893200,
              "time": "2024-02-02 12:00",
              "temp_c": -0.9,
              "temp_f": 30.4,
              "is_day": 1,
              "condition": {
                "text": "Cloudy ",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                "code": 1006
              },
              "wind_mph": 9.2,
              "wind_kph": 14.8,
              "wind_degree": 350,
              "wind_dir": "N",
              "pressure_mb": 1018,
              "pressure_in": 30.06,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 87,
              "cloud": 69,
              "feelslike_c": -5.5,
              "feelslike_f": 22.1,
              "windchill_c": -5.5,
              "windchill_f": 22.1,
              "heatindex_c": -0.9,
              "heatindex_f": 30.4,
              "dewpoint_c": -2.7,
              "dewpoint_f": 27.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 11.9,
              "gust_kph": 19.2,
              "uv": 1,
              "short_rad": 167.56,
              "diff_rad": 60.33
            },
            {
              "time_epoch": 1706896800,
              "time": "2024-02-02 13:00",
              "temp_c": -0.7,
              "temp_f": 30.8,
              "is_day": 1,
              "condition": {
                "text": "Cloudy ",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                "code": 1006
              },
              "wind_mph": 8.9,
              "wind_kph": 14.4,
              "wind_degree": 347,
              "wind_dir": "NNW",
              "pressure_mb": 1018,
              "pressure_in": 30.05,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 89,
              "cloud": 73,
              "feelslike_c": -5.1,
              "feelslike_f": 22.8,
              "windchill_c": -5.1,
              "windchill_f": 22.8,
              "heatindex_c": -0.7,
              "heatindex_f": 30.8,
              "dewpoint_c": -2.3,
              "dewpoint_f": 27.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 11.7,
              "gust_kph": 18.8,
              "uv": 1,
              "short_rad": 224.78,
              "diff_rad": 70.04
            },
            {
              "time_epoch": 1706900400,
              "time": "2024-02-02 14:00",
              "temp_c": -0.5,
              "temp_f": 31.1,
              "is_day": 1,
              "condition": {
                "text": "Overcast ",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                "code": 1009
              },
              "wind_mph": 8.7,
              "wind_kph": 14,
              "wind_degree": 341,
              "wind_dir": "NNW",
              "pressure_mb": 1018,
              "pressure_in": 30.05,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 88,
              "cloud": 90,
              "feelslike_c": -4.9,
              "feelslike_f": 23.2,
              "windchill_c": -4.9,
              "windchill_f": 23.2,
              "heatindex_c": -0.5,
              "heatindex_f": 31.1,
              "dewpoint_c": -2.3,
              "dewpoint_f": 28,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 11.4,
              "gust_kph": 18.4,
              "uv": 1,
              "short_rad": 262.98,
              "diff_rad": 81.66
            },
            {
              "time_epoch": 1706904000,
              "time": "2024-02-02 15:00",
              "temp_c": -0.4,
              "temp_f": 31.3,
              "is_day": 1,
              "condition": {
                "text": "Light freezing rain",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/311.png",
                "code": 1198
              },
              "wind_mph": 8.7,
              "wind_kph": 14,
              "wind_degree": 342,
              "wind_dir": "NNW",
              "pressure_mb": 1018,
              "pressure_in": 30.05,
              "precip_mm": 0.01,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 86,
              "cloud": 100,
              "feelslike_c": -4.7,
              "feelslike_f": 23.6,
              "windchill_c": -4.7,
              "windchill_f": 23.6,
              "heatindex_c": -0.4,
              "heatindex_f": 31.4,
              "dewpoint_c": -2.4,
              "dewpoint_f": 27.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 71,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 11.5,
              "gust_kph": 18.5,
              "uv": 1,
              "short_rad": 384.92,
              "diff_rad": 146.74
            },
            {
              "time_epoch": 1706907600,
              "time": "2024-02-02 16:00",
              "temp_c": -0.7,
              "temp_f": 30.8,
              "is_day": 1,
              "condition": {
                "text": "Light freezing rain",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/311.png",
                "code": 1198
              },
              "wind_mph": 8.7,
              "wind_kph": 14,
              "wind_degree": 347,
              "wind_dir": "NNW",
              "pressure_mb": 1018,
              "pressure_in": 30.07,
              "precip_mm": 0.01,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 84,
              "cloud": 85,
              "feelslike_c": -5.1,
              "feelslike_f": 22.9,
              "windchill_c": -5.1,
              "windchill_f": 22.9,
              "heatindex_c": -0.7,
              "heatindex_f": 30.8,
              "dewpoint_c": -2.5,
              "dewpoint_f": 27.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 1,
              "chance_of_snow": 87,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 11.6,
              "gust_kph": 18.6,
              "uv": 1,
              "short_rad": 345.78,
              "diff_rad": 131.33
            },
            {
              "time_epoch": 1706911200,
              "time": "2024-02-02 17:00",
              "temp_c": -1.7,
              "temp_f": 28.9,
              "is_day": 1,
              "condition": {
                "text": "Cloudy ",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                "code": 1006
              },
              "wind_mph": 8.7,
              "wind_kph": 14,
              "wind_degree": 352,
              "wind_dir": "N",
              "pressure_mb": 1019,
              "pressure_in": 30.08,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 84,
              "cloud": 65,
              "feelslike_c": -6,
              "feelslike_f": 21.2,
              "windchill_c": -6,
              "windchill_f": 21.2,
              "heatindex_c": -1.7,
              "heatindex_f": 28.9,
              "dewpoint_c": -3.3,
              "dewpoint_f": 26,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 12.7,
              "gust_kph": 20.4,
              "uv": 1,
              "short_rad": 289.68,
              "diff_rad": 113
            },
            {
              "time_epoch": 1706914800,
              "time": "2024-02-02 18:00",
              "temp_c": -3.4,
              "temp_f": 25.9,
              "is_day": 0,
              "condition": {
                "text": "Cloudy ",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                "code": 1006
              },
              "wind_mph": 6.9,
              "wind_kph": 11.2,
              "wind_degree": 353,
              "wind_dir": "N",
              "pressure_mb": 1019,
              "pressure_in": 30.1,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 87,
              "cloud": 63,
              "feelslike_c": -7.5,
              "feelslike_f": 18.5,
              "windchill_c": -7.5,
              "windchill_f": 18.5,
              "heatindex_c": -3.4,
              "heatindex_f": 25.9,
              "dewpoint_c": -4.7,
              "dewpoint_f": 23.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 12.1,
              "gust_kph": 19.5,
              "uv": 1,
              "short_rad": 229.08,
              "diff_rad": 90.3
            },
            {
              "time_epoch": 1706918400,
              "time": "2024-02-02 19:00",
              "temp_c": -4.4,
              "temp_f": 24.1,
              "is_day": 0,
              "condition": {
                "text": "Cloudy ",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                "code": 1006
              },
              "wind_mph": 5.6,
              "wind_kph": 9,
              "wind_degree": 343,
              "wind_dir": "NNW",
              "pressure_mb": 1020,
              "pressure_in": 30.13,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 91,
              "cloud": 85,
              "feelslike_c": -8.5,
              "feelslike_f": 16.7,
              "windchill_c": -8.5,
              "windchill_f": 16.7,
              "heatindex_c": -4.4,
              "heatindex_f": 24.1,
              "dewpoint_c": -6.3,
              "dewpoint_f": 20.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 11.7,
              "gust_kph": 18.9,
              "uv": 1,
              "short_rad": 183.3,
              "diff_rad": 72.26
            },
            {
              "time_epoch": 1706922000,
              "time": "2024-02-02 20:00",
              "temp_c": -4.4,
              "temp_f": 24,
              "is_day": 0,
              "condition": {
                "text": "Overcast ",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                "code": 1009
              },
              "wind_mph": 5.6,
              "wind_kph": 9,
              "wind_degree": 345,
              "wind_dir": "NNW",
              "pressure_mb": 1021,
              "pressure_in": 30.14,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 90,
              "cloud": 90,
              "feelslike_c": -8.5,
              "feelslike_f": 16.6,
              "windchill_c": -8.5,
              "windchill_f": 16.6,
              "heatindex_c": -4.4,
              "heatindex_f": 24,
              "dewpoint_c": -6.8,
              "dewpoint_f": 19.8,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 11.7,
              "gust_kph": 18.9,
              "uv": 1,
              "short_rad": 152.75,
              "diff_rad": 60.22
            },
            {
              "time_epoch": 1706925600,
              "time": "2024-02-02 21:00",
              "temp_c": -4.3,
              "temp_f": 24.2,
              "is_day": 0,
              "condition": {
                "text": "Overcast ",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                "code": 1009
              },
              "wind_mph": 6,
              "wind_kph": 9.7,
              "wind_degree": 352,
              "wind_dir": "N",
              "pressure_mb": 1021,
              "pressure_in": 30.15,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 88,
              "cloud": 94,
              "feelslike_c": -8.3,
              "feelslike_f": 17.1,
              "windchill_c": -8.3,
              "windchill_f": 17.1,
              "heatindex_c": -4.3,
              "heatindex_f": 24.2,
              "dewpoint_c": -6.1,
              "dewpoint_f": 21,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 11.9,
              "gust_kph": 19.1,
              "uv": 1,
              "short_rad": 0,
              "diff_rad": 0
            },
            {
              "time_epoch": 1706929200,
              "time": "2024-02-02 22:00",
              "temp_c": -5.3,
              "temp_f": 22.5,
              "is_day": 0,
              "condition": {
                "text": "Partly Cloudy ",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 5.6,
              "wind_kph": 9,
              "wind_degree": 351,
              "wind_dir": "N",
              "pressure_mb": 1021,
              "pressure_in": 30.16,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 88,
              "cloud": 56,
              "feelslike_c": -9.1,
              "feelslike_f": 15.5,
              "windchill_c": -9.1,
              "windchill_f": 15.5,
              "heatindex_c": -5.3,
              "heatindex_f": 22.5,
              "dewpoint_c": -5.9,
              "dewpoint_f": 21.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 10.6,
              "gust_kph": 17.1,
              "uv": 1,
              "short_rad": 0,
              "diff_rad": 0
            },
            {
              "time_epoch": 1706932800,
              "time": "2024-02-02 23:00",
              "temp_c": -6.5,
              "temp_f": 20.4,
              "is_day": 0,
              "condition": {
                "text": "Clear ",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 4.9,
              "wind_kph": 7.9,
              "wind_degree": 348,
              "wind_dir": "NNW",
              "pressure_mb": 1021,
              "pressure_in": 30.16,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 91,
              "cloud": 23,
              "feelslike_c": -10.4,
              "feelslike_f": 13.4,
              "windchill_c": -10.4,
              "windchill_f": 13.4,
              "heatindex_c": -6.5,
              "heatindex_f": 20.4,
              "dewpoint_c": -7.4,
              "dewpoint_f": 18.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 10.3,
              "gust_kph": 16.6,
              "uv": 1,
              "short_rad": 0,
              "diff_rad": 0
            }
          ]
        },
        {
          "date": "2024-02-03",
          "date_epoch": 1706918400,
          "day": {
            "maxtemp_c": -1.8,
            "maxtemp_f": 28.7,
            "mintemp_c": -12,
            "mintemp_f": 10.4,
            "avgtemp_c": -7.6,
            "avgtemp_f": 18.4,
            "maxwind_mph": 4.7,
            "maxwind_kph": 7.6,
            "totalprecip_mm": 0,
            "totalprecip_in": 0,
            "totalsnow_cm": 0,
            "avgvis_km": 5.7,
            "avgvis_miles": 3,
            "avghumidity": 90,
            "daily_will_it_rain": 0,
            "daily_chance_of_rain": 0,
            "daily_will_it_snow": 0,
            "daily_chance_of_snow": 0,
            "condition": {
              "text": "Partly Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "uv": 2
          },
          "astro": {
            "sunrise": "07:22 AM",
            "sunset": "05:12 PM",
            "moonrise": "01:32 AM",
            "moonset": "10:52 AM",
            "moon_phase": "Waning Crescent",
            "moon_illumination": 50,
            "is_moon_up": 0,
            "is_sun_up": 0
          },
          "hour": [
            {
              "time_epoch": 1706936400,
              "time": "2024-02-03 00:00",
              "temp_c": -7.7,
              "temp_f": 18.2,
              "is_day": 0,
              "condition": {
                "text": "Clear ",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
              },
              "wind_mph": 4.7,
              "wind_kph": 7.6,
              "wind_degree": 348,
              "wind_dir": "NNW",
              "pressure_mb": 1021,
              "pressure_in": 30.16,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 93,
              "cloud": 24,
              "feelslike_c": -11.7,
              "feelslike_f": 11,
              "windchill_c": -11.7,
              "windchill_f": 11,
              "heatindex_c": -7.7,
              "heatindex_f": 18.2,
              "dewpoint_c": -8.6,
              "dewpoint_f": 16.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 9.9,
              "gust_kph": 15.9,
              "uv": 1,
              "short_rad": 0,
              "diff_rad": 0
            },
            {
              "time_epoch": 1706940000,
              "time": "2024-02-03 01:00",
              "temp_c": -8.7,
              "temp_f": 16.3,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 4.7,
              "wind_kph": 7.6,
              "wind_degree": 350,
              "wind_dir": "N",
              "pressure_mb": 1022,
              "pressure_in": 30.17,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 94,
              "cloud": 38,
              "feelslike_c": -12.7,
              "feelslike_f": 9.2,
              "windchill_c": -12.7,
              "windchill_f": 9.2,
              "heatindex_c": -8.7,
              "heatindex_f": 16.3,
              "dewpoint_c": -9.6,
              "dewpoint_f": 14.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 9.9,
              "gust_kph": 15.9,
              "uv": 1,
              "short_rad": 0,
              "diff_rad": 0
            },
            {
              "time_epoch": 1706943600,
              "time": "2024-02-03 02:00",
              "temp_c": -9.5,
              "temp_f": 15,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 4.3,
              "wind_kph": 6.8,
              "wind_degree": 351,
              "wind_dir": "N",
              "pressure_mb": 1021,
              "pressure_in": 30.16,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 95,
              "cloud": 40,
              "feelslike_c": -13.2,
              "feelslike_f": 8.2,
              "windchill_c": -13.2,
              "windchill_f": 8.2,
              "heatindex_c": -9.5,
              "heatindex_f": 15,
              "dewpoint_c": -10.5,
              "dewpoint_f": 13.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 8.9,
              "gust_kph": 14.4,
              "uv": 1,
              "short_rad": 0,
              "diff_rad": 0
            },
            {
              "time_epoch": 1706947200,
              "time": "2024-02-03 03:00",
              "temp_c": -10.2,
              "temp_f": 13.7,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 3.8,
              "wind_kph": 6.1,
              "wind_degree": 350,
              "wind_dir": "N",
              "pressure_mb": 1022,
              "pressure_in": 30.18,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 95,
              "cloud": 46,
              "feelslike_c": -13.8,
              "feelslike_f": 7.1,
              "windchill_c": -13.8,
              "windchill_f": 7.1,
              "heatindex_c": -10.2,
              "heatindex_f": 13.7,
              "dewpoint_c": -10.8,
              "dewpoint_f": 12.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 8,
              "gust_kph": 12.9,
              "uv": 1,
              "short_rad": 0,
              "diff_rad": 0
            },
            {
              "time_epoch": 1706950800,
              "time": "2024-02-03 04:00",
              "temp_c": -10.9,
              "temp_f": 12.3,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 3.6,
              "wind_kph": 5.8,
              "wind_degree": 344,
              "wind_dir": "NNW",
              "pressure_mb": 1022,
              "pressure_in": 30.18,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 95,
              "cloud": 46,
              "feelslike_c": -14.6,
              "feelslike_f": 5.7,
              "windchill_c": -14.6,
              "windchill_f": 5.7,
              "heatindex_c": -10.9,
              "heatindex_f": 12.3,
              "dewpoint_c": -11.5,
              "dewpoint_f": 11.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 7.5,
              "gust_kph": 12.1,
              "uv": 1,
              "short_rad": 0,
              "diff_rad": 0
            },
            {
              "time_epoch": 1706954400,
              "time": "2024-02-03 05:00",
              "temp_c": -11.4,
              "temp_f": 11.4,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 3.6,
              "wind_kph": 5.8,
              "wind_degree": 347,
              "wind_dir": "NNW",
              "pressure_mb": 1022,
              "pressure_in": 30.19,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 96,
              "cloud": 39,
              "feelslike_c": -15.2,
              "feelslike_f": 4.7,
              "windchill_c": -15.2,
              "windchill_f": 4.7,
              "heatindex_c": -11.4,
              "heatindex_f": 11.4,
              "dewpoint_c": -12.2,
              "dewpoint_f": 10,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 7.5,
              "gust_kph": 12.1,
              "uv": 1,
              "short_rad": 0,
              "diff_rad": 0
            },
            {
              "time_epoch": 1706958000,
              "time": "2024-02-03 06:00",
              "temp_c": -11.7,
              "temp_f": 10.9,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 3.8,
              "wind_kph": 6.1,
              "wind_degree": 344,
              "wind_dir": "NNW",
              "pressure_mb": 1023,
              "pressure_in": 30.2,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 96,
              "cloud": 56,
              "feelslike_c": -15.4,
              "feelslike_f": 4.2,
              "windchill_c": -15.4,
              "windchill_f": 4.2,
              "heatindex_c": -11.7,
              "heatindex_f": 10.9,
              "dewpoint_c": -12.5,
              "dewpoint_f": 9.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 8,
              "gust_kph": 12.9,
              "uv": 1,
              "short_rad": 0,
              "diff_rad": 0
            },
            {
              "time_epoch": 1706961600,
              "time": "2024-02-03 07:00",
              "temp_c": -11.9,
              "temp_f": 10.7,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 3.6,
              "wind_kph": 5.8,
              "wind_degree": 346,
              "wind_dir": "NNW",
              "pressure_mb": 1023,
              "pressure_in": 30.21,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 95,
              "cloud": 45,
              "feelslike_c": -15.7,
              "feelslike_f": 3.8,
              "windchill_c": -15.7,
              "windchill_f": 3.8,
              "heatindex_c": -11.9,
              "heatindex_f": 10.6,
              "dewpoint_c": -12.6,
              "dewpoint_f": 9.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 7.5,
              "gust_kph": 12.1,
              "uv": 1,
              "short_rad": 0,
              "diff_rad": 0
            },
            {
              "time_epoch": 1706965200,
              "time": "2024-02-03 08:00",
              "temp_c": -11.6,
              "temp_f": 11.2,
              "is_day": 1,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/143.png",
                "code": 1030
              },
              "wind_mph": 3.8,
              "wind_kph": 6.1,
              "wind_degree": 344,
              "wind_dir": "NNW",
              "pressure_mb": 1023,
              "pressure_in": 30.21,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 95,
              "cloud": 100,
              "feelslike_c": -15.4,
              "feelslike_f": 4.3,
              "windchill_c": -15.4,
              "windchill_f": 4.3,
              "heatindex_c": -11.6,
              "heatindex_f": 11.2,
              "dewpoint_c": -12.6,
              "dewpoint_f": 9.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 8,
              "gust_kph": 12.9,
              "uv": 1,
              "short_rad": 0,
              "diff_rad": 0
            },
            {
              "time_epoch": 1706968800,
              "time": "2024-02-03 09:00",
              "temp_c": -10.1,
              "temp_f": 13.9,
              "is_day": 1,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/143.png",
                "code": 1030
              },
              "wind_mph": 3.8,
              "wind_kph": 6.1,
              "wind_degree": 337,
              "wind_dir": "NNW",
              "pressure_mb": 1023,
              "pressure_in": 30.22,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 94,
              "cloud": 59,
              "feelslike_c": -13.4,
              "feelslike_f": 7.9,
              "windchill_c": -13.4,
              "windchill_f": 7.9,
              "heatindex_c": -10.1,
              "heatindex_f": 13.8,
              "dewpoint_c": -12,
              "dewpoint_f": 10.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 8,
              "gust_kph": 12.9,
              "uv": 1,
              "short_rad": 11.7,
              "diff_rad": 5.31
            },
            {
              "time_epoch": 1706972400,
              "time": "2024-02-03 10:00",
              "temp_c": -8.3,
              "temp_f": 17.1,
              "is_day": 1,
              "condition": {
                "text": "Overcast ",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                "code": 1009
              },
              "wind_mph": 3.1,
              "wind_kph": 5,
              "wind_degree": 340,
              "wind_dir": "NNW",
              "pressure_mb": 1023,
              "pressure_in": 30.21,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 90,
              "cloud": 88,
              "feelslike_c": -11,
              "feelslike_f": 12.2,
              "windchill_c": -11,
              "windchill_f": 12.2,
              "heatindex_c": -8.3,
              "heatindex_f": 17.1,
              "dewpoint_c": -10,
              "dewpoint_f": 14.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 5,
              "gust_kph": 8,
              "uv": 1,
              "short_rad": 65.6,
              "diff_rad": 25.8
            },
            {
              "time_epoch": 1706976000,
              "time": "2024-02-03 11:00",
              "temp_c": -6.5,
              "temp_f": 20.3,
              "is_day": 1,
              "condition": {
                "text": "Cloudy ",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                "code": 1006
              },
              "wind_mph": 2.9,
              "wind_kph": 4.7,
              "wind_degree": 353,
              "wind_dir": "N",
              "pressure_mb": 1023,
              "pressure_in": 30.21,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 86,
              "cloud": 72,
              "feelslike_c": -8.4,
              "feelslike_f": 16.9,
              "windchill_c": -8.4,
              "windchill_f": 16.9,
              "heatindex_c": -6.5,
              "heatindex_f": 20.3,
              "dewpoint_c": -8.4,
              "dewpoint_f": 16.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 3.7,
              "gust_kph": 6,
              "uv": 1,
              "short_rad": 126.62,
              "diff_rad": 49.2
            },
            {
              "time_epoch": 1706979600,
              "time": "2024-02-03 12:00",
              "temp_c": -5,
              "temp_f": 22.9,
              "is_day": 1,
              "condition": {
                "text": "Partly Cloudy ",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 2,
              "wind_kph": 3.2,
              "wind_degree": 359,
              "wind_dir": "N",
              "pressure_mb": 1023,
              "pressure_in": 30.21,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 82,
              "cloud": 47,
              "feelslike_c": -6.5,
              "feelslike_f": 20.3,
              "windchill_c": -6.5,
              "windchill_f": 20.3,
              "heatindex_c": -5,
              "heatindex_f": 22.9,
              "dewpoint_c": -7.3,
              "dewpoint_f": 18.9,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 2.4,
              "gust_kph": 3.9,
              "uv": 2,
              "short_rad": 191.04,
              "diff_rad": 58.9
            },
            {
              "time_epoch": 1706983200,
              "time": "2024-02-03 13:00",
              "temp_c": -3.9,
              "temp_f": 25,
              "is_day": 1,
              "condition": {
                "text": "Partly Cloudy ",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 2,
              "wind_kph": 3.2,
              "wind_degree": 323,
              "wind_dir": "NW",
              "pressure_mb": 1022,
              "pressure_in": 30.19,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 80,
              "cloud": 44,
              "feelslike_c": -5.1,
              "feelslike_f": 22.9,
              "windchill_c": -5.1,
              "windchill_f": 22.9,
              "heatindex_c": -3.9,
              "heatindex_f": 25,
              "dewpoint_c": -6.6,
              "dewpoint_f": 20.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 2.4,
              "gust_kph": 3.9,
              "uv": 2,
              "short_rad": 240.5,
              "diff_rad": 73.5
            },
            {
              "time_epoch": 1706986800,
              "time": "2024-02-03 14:00",
              "temp_c": -3,
              "temp_f": 26.5,
              "is_day": 1,
              "condition": {
                "text": "Partly Cloudy ",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 2,
              "wind_kph": 3.2,
              "wind_degree": 312,
              "wind_dir": "NW",
              "pressure_mb": 1022,
              "pressure_in": 30.17,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 78,
              "cloud": 44,
              "feelslike_c": -4.4,
              "feelslike_f": 24.1,
              "windchill_c": -4.4,
              "windchill_f": 24.1,
              "heatindex_c": -3,
              "heatindex_f": 26.5,
              "dewpoint_c": -6,
              "dewpoint_f": 21.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 2.5,
              "gust_kph": 4,
              "uv": 2,
              "short_rad": 269.98,
              "diff_rad": 90.1
            },
            {
              "time_epoch": 1706990400,
              "time": "2024-02-03 15:00",
              "temp_c": -2.4,
              "temp_f": 27.6,
              "is_day": 1,
              "condition": {
                "text": "Partly Cloudy ",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 2.7,
              "wind_kph": 4.3,
              "wind_degree": 290,
              "wind_dir": "WNW",
              "pressure_mb": 1021,
              "pressure_in": 30.15,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 77,
              "cloud": 47,
              "feelslike_c": -3.9,
              "feelslike_f": 24.9,
              "windchill_c": -3.9,
              "windchill_f": 24.9,
              "heatindex_c": -2.4,
              "heatindex_f": 27.6,
              "dewpoint_c": -5.7,
              "dewpoint_f": 21.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 3.4,
              "gust_kph": 5.5,
              "uv": 2,
              "short_rad": 382.8,
              "diff_rad": 157.19
            },
            {
              "time_epoch": 1706994000,
              "time": "2024-02-03 16:00",
              "temp_c": -2.3,
              "temp_f": 27.8,
              "is_day": 1,
              "condition": {
                "text": "Partly Cloudy ",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 2.9,
              "wind_kph": 4.7,
              "wind_degree": 282,
              "wind_dir": "WNW",
              "pressure_mb": 1021,
              "pressure_in": 30.14,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 76,
              "cloud": 44,
              "feelslike_c": -4.1,
              "feelslike_f": 24.6,
              "windchill_c": -4.1,
              "windchill_f": 24.6,
              "heatindex_c": -2.3,
              "heatindex_f": 27.8,
              "dewpoint_c": -5.5,
              "dewpoint_f": 22.2,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 3.8,
              "gust_kph": 6.2,
              "uv": 2,
              "short_rad": 354.62,
              "diff_rad": 133.05
            },
            {
              "time_epoch": 1706997600,
              "time": "2024-02-03 17:00",
              "temp_c": -3.5,
              "temp_f": 25.8,
              "is_day": 1,
              "condition": {
                "text": "Partly Cloudy ",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
              },
              "wind_mph": 3.4,
              "wind_kph": 5.4,
              "wind_degree": 254,
              "wind_dir": "WSW",
              "pressure_mb": 1020,
              "pressure_in": 30.13,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 86,
              "cloud": 44,
              "feelslike_c": -5.6,
              "feelslike_f": 22,
              "windchill_c": -5.6,
              "windchill_f": 22,
              "heatindex_c": -3.4,
              "heatindex_f": 25.8,
              "dewpoint_c": -4.3,
              "dewpoint_f": 24.3,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 4.9,
              "gust_kph": 7.8,
              "uv": 2,
              "short_rad": 296.28,
              "diff_rad": 114.46
            },
            {
              "time_epoch": 1707001200,
              "time": "2024-02-03 18:00",
              "temp_c": -4.8,
              "temp_f": 23.3,
              "is_day": 0,
              "condition": {
                "text": "Partly Cloudy ",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 3.4,
              "wind_kph": 5.4,
              "wind_degree": 243,
              "wind_dir": "WSW",
              "pressure_mb": 1020,
              "pressure_in": 30.13,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 91,
              "cloud": 46,
              "feelslike_c": -7.1,
              "feelslike_f": 19.2,
              "windchill_c": -7.1,
              "windchill_f": 19.2,
              "heatindex_c": -4.8,
              "heatindex_f": 23.3,
              "dewpoint_c": -5.8,
              "dewpoint_f": 21.6,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 6.9,
              "gust_kph": 11.1,
              "uv": 1,
              "short_rad": 235.16,
              "diff_rad": 91.9
            },
            {
              "time_epoch": 1707004800,
              "time": "2024-02-03 19:00",
              "temp_c": -5.9,
              "temp_f": 21.3,
              "is_day": 0,
              "condition": {
                "text": "Partly Cloudy ",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
              },
              "wind_mph": 3.1,
              "wind_kph": 5,
              "wind_degree": 267,
              "wind_dir": "W",
              "pressure_mb": 1021,
              "pressure_in": 30.14,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 93,
              "cloud": 46,
              "feelslike_c": -8.2,
              "feelslike_f": 17.2,
              "windchill_c": -8.2,
              "windchill_f": 17.2,
              "heatindex_c": -5.9,
              "heatindex_f": 21.3,
              "dewpoint_c": -7.2,
              "dewpoint_f": 19.1,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 10,
              "vis_miles": 6,
              "gust_mph": 6.6,
              "gust_kph": 10.6,
              "uv": 1,
              "short_rad": 188.2,
              "diff_rad": 73.55
            },
            {
              "time_epoch": 1707008400,
              "time": "2024-02-03 20:00",
              "temp_c": -6.9,
              "temp_f": 19.7,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 2.9,
              "wind_kph": 4.7,
              "wind_degree": 288,
              "wind_dir": "WNW",
              "pressure_mb": 1021,
              "pressure_in": 30.14,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 94,
              "cloud": 49,
              "feelslike_c": -9.1,
              "feelslike_f": 15.6,
              "windchill_c": -9.1,
              "windchill_f": 15.6,
              "heatindex_c": -6.9,
              "heatindex_f": 19.7,
              "dewpoint_c": -7.8,
              "dewpoint_f": 18,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 6.1,
              "gust_kph": 9.8,
              "uv": 1,
              "short_rad": 156.83,
              "diff_rad": 61.3
            },
            {
              "time_epoch": 1707012000,
              "time": "2024-02-03 21:00",
              "temp_c": -7.7,
              "temp_f": 18.2,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 2.7,
              "wind_kph": 4.3,
              "wind_degree": 296,
              "wind_dir": "WNW",
              "pressure_mb": 1021,
              "pressure_in": 30.15,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 95,
              "cloud": 49,
              "feelslike_c": -9.9,
              "feelslike_f": 14.1,
              "windchill_c": -9.9,
              "windchill_f": 14.1,
              "heatindex_c": -7.7,
              "heatindex_f": 18.2,
              "dewpoint_c": -8.5,
              "dewpoint_f": 16.7,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 5.6,
              "gust_kph": 9.1,
              "uv": 1,
              "short_rad": 0,
              "diff_rad": 0
            },
            {
              "time_epoch": 1707015600,
              "time": "2024-02-03 22:00",
              "temp_c": -8.4,
              "temp_f": 16.9,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 2.7,
              "wind_kph": 4.3,
              "wind_degree": 309,
              "wind_dir": "NW",
              "pressure_mb": 1021,
              "pressure_in": 30.15,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 95,
              "cloud": 45,
              "feelslike_c": -10.4,
              "feelslike_f": 13.2,
              "windchill_c": -10.4,
              "windchill_f": 13.2,
              "heatindex_c": -8.4,
              "heatindex_f": 16.9,
              "dewpoint_c": -9.1,
              "dewpoint_f": 15.5,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 5.6,
              "gust_kph": 9.1,
              "uv": 1,
              "short_rad": 0,
              "diff_rad": 0
            },
            {
              "time_epoch": 1707019200,
              "time": "2024-02-03 23:00",
              "temp_c": -9.1,
              "temp_f": 15.6,
              "is_day": 0,
              "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
              },
              "wind_mph": 2.2,
              "wind_kph": 3.6,
              "wind_degree": 311,
              "wind_dir": "NW",
              "pressure_mb": 1021,
              "pressure_in": 30.14,
              "precip_mm": 0,
              "precip_in": 0,
              "snow_cm": 0,
              "humidity": 95,
              "cloud": 41,
              "feelslike_c": -11.1,
              "feelslike_f": 12,
              "windchill_c": -11.1,
              "windchill_f": 12,
              "heatindex_c": -9.1,
              "heatindex_f": 15.6,
              "dewpoint_c": -9.8,
              "dewpoint_f": 14.4,
              "will_it_rain": 0,
              "chance_of_rain": 0,
              "will_it_snow": 0,
              "chance_of_snow": 0,
              "vis_km": 2,
              "vis_miles": 1,
              "gust_mph": 4.7,
              "gust_kph": 7.6,
              "uv": 1,
              "short_rad": 0,
              "diff_rad": 0
            }
          ]
        }
      ]
    }
  }